### PR TITLE
Rename files

### PR DESCRIPTION
**Pull request by sebglane**
Review after merging PR #110

### CODE REVIEW

**Comment by sebglane** [comment]
Review after merging PR #110

**Comment by sebglane** [comment]
Ready for review.

**Review by j507 — COMMENTED** [review]
Why the rename here?

**Comment by sebglane** [comment]
> Why the rename here?

Renaming files from `heat_equation*.*` to `convection_diffusion*.*` first to keep changes small. Later the namespaces and classes are also renamed.

**Comment by j507** [comment]
I meant what is the reasoning behind the name change. While it is true that by neglecting mechanical dissipation the heat equation reduces to the general convection diffusion equation for an incompressible flow, it is more practical to write a general heat equation, i.e. with a mechanical dissipation term, with whom, by ignoring some of its terms, one can also model diffusion problems, i.e. compositional diffusion, which I suspect is your motivation behind the change.
I know that the mechanical dissipation term is neglected in the Boussinesq approximation but adding it to the solver expands the range of possible uses of the solvers suite.
Furthermore the rename would also require rewriting some of its documentation and internal members for consistency.

**Comment by sebglane** [comment]
> I meant what is the reasoning behind the name change. While it is true that by neglecting mechanical dissipation the heat equation reduces to the general convection diffusion equation for an incompressible flow, it is more practical to write a general heat equation, i.e. with a mechanical dissipation term, with whom, by ignoring some of its terms, one can also model diffusion problems, i.e. compositional diffusion, which I suspect is your motivation behind the change.

At the moment, the solver solves a convection diffusion problem. Therefore, I decided to rename it.

My motivation is that compositional convection (double diffusion) is also an important mechanism at CMB. In these problem an additional convection diffusion equation for a compositional field is solved. Moreover, if you are really strict regarding the thermodynamic derivation. The variable which we call temperature is, in a generalized framework, a thermal variable. In some formulations, for example, in the anelastic limit, it is actually the entropy. 

> I know that the mechanical dissipation term is neglected in the Boussinesq approximation but adding it to the solver expands the range of possible uses of the solvers suite.

If we want to solve something different than a convection diffusion equation including a source term for this thermal variable, we may want to extend the current solver or create a child of the current class.

> Furthermore the rename would also require rewriting some of its documentation and internal members for consistency.

I will quickly go through the code now and replace temperature by field variable but I can live with some inconsistencies in the docs at the moment.

**Comment by j507** [comment]
> My motivation is that compositional convection (double diffusion) is also an important mechanism at CMB. In these problem an additional convection diffusion equation for a compositional field is solved. Moreover, if you are really strict regarding the thermodynamic derivation. The variable which we call temperature is, in a generalized framework, a thermal variable. In some formulations, for example, in the anelastic limit, it is actually the entropy. 
> 
> If we want to solve something different than a convection diffusion equation including a source term for this thermal variable, we may want to extend the current solver or create a child of the current class.

Okay, I understand. Feel free to merge.

**Pull request merged**
