### PR TITLE
Tests for a convection diffusion problem

### PR DESCRIPTION
**Pull request by sebglane**
After #124 and #132

### CODE REVIEW

**Comment by sebglane** [comment]
Now this is ready for review after merging `master`.

**Comment by j507** [comment]
What is the meaning of the convergence rates here?

**Comment by sebglane** [comment]
> What is the meaning of the convergence rates here?

I don't understand your question. They are computed in the same way as for the pure diffusion problem. This PR should only consider the convection diffusion problem.

**Comment by sebglane** [comment]
** We need to change the base to `master` after the review! **

**Comment by j507** [comment]
> > What is the meaning of the convergence rates here?
> 
> I don't understand your question. They are computed in the same way as for the pure diffusion problem. This PR should only consider the convection diffusion problem.

Sorry, I meant the behavior and values of the convergence rates seem weird to me. As mentioned  

> > What is the meaning of the convergence rates here?
> 
> I don't understand your question. They are computed in the same way as for the pure diffusion problem. This PR should only consider the convection diffusion problem.

The convergence rates exhibit the same behavior as in #132. I will redo this tests with a manufacture solution.

**Review by j507 — APPROVED** [review]
I will change the tests in a different PR

**Pull request merged**
