### PR TITLE
Grid generation utility

### PR DESCRIPTION
**Pull request by sebglane**
I replaced some of the manually generated meshes by those generated by deal.ii. The DFG benchmark mesh is mostly copy-paste from the deal.ii source code.

### CODE REVIEW

**Review by j507 — CHANGES_REQUESTED** [review]
I will do the changes when I get the Christensen benchmark running.

**Comment by sebglane** [comment]
Why did you merge this?

**Comment by j507** [comment]
> Why did you merge this?

I think it got merged automatically by merging #124

**Comment by j507** [comment]
Should I revert it?

**Comment by sebglane** [comment]
No I think it is okay if it was automatically merged by github. Probably it was marked as merged because the commit in `grid_generation_utility` were contained in `add_ctest`. But I guess I overwrote all of changes later.

**Pull request merged**
